---
title: "Methodology and Notes"
toc: true
toc-title: "Skip to..."
toc-depth: 2
navbar: false
echo: false
results: asis
embed-resources: false
bibliography: bibliography.bib
cite-method: natbib
---

<a href="index.html">Take me back to the report!</a>

On this page, I briefly summarize some of the techniques used to generate the visualizations in the report.  All code will be linked on my github after the project is de-anonymized.

## Network Analysis

**Section name:** "Untangling The Web of Job Titles"

These network visualizations were generated using a combination of the <a href="https://textnets.readthedocs.io/en/stable/index.html" target="_blank">textnets</a> and <a href="https://pyviz.org/" target="_blank">pyviz</a> packages.  Creating the network visualization required a few steps:

1. **Text preparation:** The text data is cleaned by removing stop words, tokenizing to noun phrases, and calculating the term frequency - inverse document frequency (TF-IDF). TF-IDF is a technique used for determining important words in a document.  The noun phrases are filtered based on their TF-IDF score. 
2. **Network building:**  The documents and noun phrases are plotted as nodes, with the documents (search terms) represented as squares, and the noun phrases represented as circles.  An edge (line) is drawn between nodes that co-occur.  
3. **Community detection:** The nodes are colored by their community.  Community detection was completed using a <a href="https://leidenalg.readthedocs.io/en/stable/reference.html#rbconfigurationvertexpartition" target="_blank">Reichardt and Bornholdt’s Potts model</a>.  My understanding is that this model was appropriate because is flexible and allows for <a href="https://journals.aps.org/pre/abstract/10.1103/PhysRevE.74.016110" target="_blank">overlapping communities</a>.


## Qualifications, Responsibilities, and Benefits

**Section name:** "Great Responsibilities, Great Benefits?"

The data for the visualizations in this section was generated by counting the number of bullet points for each category listed in the job posting.  The colors of the bubble represent the search term, while the area of the circle is scaled to the number of benefits listed.  The values in the correlation matrix are simply Pearson's correlation coefficients.  Both plots were primarily generated using the <a href="https://plotly.com/python/" target="_blank">plotly</a> package in python.

## Map 

**Section name:** "Mapping Salaries"

Since the data were quite messy, a number of visualization choices needed to be made.  Here are the main decisions:

* **Finding locations and adding noise:** Jobs were either remote (listed as "anywhere" or "united states"), or they were listed at a location in *city, state abbreviation* format.
  * **For remote jobs,** coordinates were randomly assigned to a location in the continental US.  A bounding box was created in GeoJSON for this purpose.  Most of the remote jobs will appear in the central US, since drawing a bigger box often led to some jobs being located in the ocean.  To avoid any confusion, the remote jobs are not displayed by default, so the user must click on the "remote" box to show those jobs. 
  * **For in-person jobs,** the coordinates were located using the <a href="https://nominatim.org/" target="_blank">nominatim</a> API.  Since a number of jobs were listed in the same city, I needed to add a small amount of noise to the coordinates to avoid overlap (about a tenth of a degree).
* **Yearly/Hourly:** Some positions were listed as hourly wage jobs.  These were converted into yearly salaries by multiplying the wage by 2,080, which is the approximate number of hours worked in a year for a full-time employee.  This way, the jobs could be compared on the same scale.
* **Markers:** The green markers were scaled to 1/5000 of the actual salary.  The concentric circles were used to show a minimum and a maximum salary range.  A popup was generated to provide more information about the position.
* **The map:** The map was created with <a href="https://python-visualization.github.io/folium/" target="_blank">folium</a>, and used a template called "dark matter" to match the website aesthetic. 
